### ISSUE TITLE
static/images/Arch_1.svg seems outdated

### ISSUE THREAD

**Issue by AkihiroSuda** [rancher-sandbox/rancherdesktop.io#4]
https://raw.githubusercontent.com/rancher-sandbox/rancherdesktop.io/66f47537073ef212038c5f1bfed2f5a0178fc4f6/static/images/Arch_1.svg

![iimage](https://raw.githubusercontent.com/rancher-sandbox/rancherdesktop.io/66f47537073ef212038c5f1bfed2f5a0178fc4f6/static/images/Arch_1.svg)

Rancher Desktop no longer uses HyperKit, so the image should be updated

**Comment by mattfarina** [comment]
Thanks for catching that. I'll correct it.

**Comment by mook-as** [comment]
Fixed in #6 — it now uses a separate https://github.com/rancher-sandbox/rancherdesktop.io/blob/main/static/images/Arch_v2.svg
