### ISSUE TITLE
GitHub API rate limiting causes download of old installers

### ISSUE THREAD

**Issue by christianaistleitner** [rancher-sandbox/rancherdesktop.io#49]
The API call in  [DowloadButtons.tsx](https://github.com/rancher-sandbox/rancherdesktop.io/blob/main/components/DowloadButtons.tsx#L13) to fetch the latest release fails when opening the website from within large networks (corporate network, VPN) and thus the fallback version `1.10.0` is served.
This causes frustration as `1.10.0` is presented as the latest release and this fallback case is not clear to users.

```
{
    "message": "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
````

Can you please instead forward the user to `https://github.com/rancher-sandbox/rancher-desktop/releases` in the fallback case?

**Comment by jandubois** [comment]
Thanks for filing the issue; should be fixed now.

**Comment by christianaistleitner** [comment]
Wow, that was fast and I can confirm that it works, thank you!
